name: url_shorten
description: A flutter app to shorten urls
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  path: ^1.7.0
  path_provider: ^1.6.11
#  provide: ^1.0.2
  firebase_crashlytics: ^0.1.4+1
  firebase_analytics: ^5.0.16
#  dio: ^2.1.3
  rxdart: ^0.24.1
#  i18n: ^0.9.10
  quick_log: ^1.1.3
  sembast: ^2.4.7+6
  get_it: ^4.0.4
  data_connection_checker: ^0.3.4
  uuid: ^2.2.0
  http: ^0.12.2
  equatable: ^1.2.3
  validators: ^2.0.1
  google_fonts: ^1.1.0
  super_enum: ^0.4.2
  flutter_spinkit: ^4.1.2+1
  flutter_clipboard_manager: ^0.0.2
  flushbar: ^1.10.4
  dartx: ^0.5.0
  lottie: ^0.5.1
  no_bloc_flutter: ^0.3.11
  hasura: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  super_enum_generator:
  build_runner: ^1.10.0
  mockito: ^4.1.1


flutter:
  uses-material-design: true
